# Generated by Django 5.1 on 2024-09-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='work_experience',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
